import Head from "next/head";
import Navbar from "./Navbar";
import Container from '@material-ui/core/Container';

import styles from "../styles/Home.module.css";
import Home from "./Home";
export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
      <Navbar></Navbar>
        <Home />
      </div>
    
     
    </div>
  );
}
